package miniJava.SyntacticAnalyzer;

public enum TokenType {
    LPAREN, RPAREN, LSQUARE, RSQUARE, LCURLY, RCURLY, COMMA, SEMICOLON, PERIOD,
    BOOLEAN, INT,
    OPERATOR, EQUALS,
    STATIC, VOID,
    IF, ELSE, WHILE, NEW, PUBLIC, RETURN, CLASS, OR,
    IDENTIFIER, INTLITERAL, NULL, THIS, VISIBILITY,
    ERROR, EOT,
}
